### ISSUE TITLE
The test result is inconsistent with the paper

### ISSUE THREAD

**Issue by xiaobaozi1996** [kyleolsz/TB-Networks#1]
Hello, thanks for your code~
I run your code recently, but i find the result is not the same as the paper.
source : ![image](https://user-images.githubusercontent.com/31682925/67191909-1c766800-f425-11e9-8c26-b051943c35ff.png)
novel view : ![image](https://user-images.githubusercontent.com/31682925/67191949-2d26de00-f425-11e9-8b0c-8db978e7ef0e.png)
source : ![image](https://user-images.githubusercontent.com/31682925/67191964-34e68280-f425-11e9-8167-0acd2d6bf6b4.png)
novel view : ![image](https://user-images.githubusercontent.com/31682925/67191973-3a43cd00-f425-11e9-8558-66a4ba9a9c9c.png)
As it is shown above, the novel view results are not very good on the car dataset. However, it works well on the chair dataset. Is the code and the checkpoint released on the car dataset different from the paper? I use the param in the scripts/test_nvs_car.sh. Is it possible that the params are not the same with yours.
Waiting for your reply~

**Comment by kyleolsz** [comment]
With the updated model and code, this issue should be resolved. As noted, the previous model varied slightly from that used in the paper (e.g., output resolution and bottleneck dimensions). It appears that this model produced results with more variation in the output quality. The new model, which uses the same architecture as that in the paper, produces results are more consistent with those seen in the paper and supplemental material.
